import streamlit as st
import subprocess
import os

# -----------------------
# Config
# -----------------------
st.set_page_config(page_title="ZTE AI Frontend", layout="wide")
st.title("ZTE AI Frontend")
st.markdown("Type your input, and Olama will route it to the best available model.")

# -----------------------
# User Input
# -----------------------
user_input = st.text_area("Your Input", "", height=150)
run_button = st.button("Run AI")

# -----------------------
# Model Orchestration
# -----------------------
def run_olama(text: str):
    """
    Example: Orchestrates Olama as controller.
    Routes to other models (Comfy, SDXL, etc.)
    Replace with your actual local model calls.
    """
    response = ""
    try:
        # Example: call Olama CLI
        # Ensure Olama CLI is installed locally and accessible
        olama_cmd = ["olama", "generate", "--prompt", text]
        result = subprocess.run(olama_cmd, capture_output=True, text=True)
        response = result.stdout

        # Example: route to Comfy/SDXL if user_input contains certain keyword
        if "image:" in text.lower():
            # Replace this with your Comfy command
            img_prompt = text.split("image:",1)[1].strip()
            response += f"\n\n[Image generated by Comfy: {img_prompt}]"
            # Example: subprocess.run(["python3", "comfy_run.py", img_prompt])

    except Exception as e:
        response = f"Error running Olama or other models: {str(e)}"
    return response

# -----------------------
# Run on button press
# -----------------------
if run_button and user_input.strip() != "":
    st.markdown("**AI is thinking...**")
    output = run_olama(user_input)
    st.markdown("### AI says:")
    st.text(output)